package engine

import (
	"bufio"
	"go/ast"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// ExclusionChecker determines which files and lines should be skipped.
type ExclusionChecker struct {
	patterns       []string          // User-specified glob patterns
	generatedCache map[string]bool   // Cache: file -> isGenerated
	aridLineCache  map[fileLine]bool // Cache: file:line -> isArid
}

// NewExclusionChecker creates a checker with the given user patterns.
func NewExclusionChecker(patterns []string) *ExclusionChecker {
	return &ExclusionChecker{
		patterns:       patterns,
		generatedCache: make(map[string]bool),
		aridLineCache:  make(map[fileLine]bool),
	}
}

// ShouldExcludeFile returns true if the entire file should be skipped.
func (ec *ExclusionChecker) ShouldExcludeFile(filename string) bool {
	// Test files
	if strings.HasSuffix(filename, "_test.go") {
		return true
	}

	// Directory-based exclusions
	for _, segment := range excludedDirs {
		if containsPathSegment(filename, segment) {
			return true
		}
	}

	// Filename patterns for common generated files
	base := filepath.Base(filename)
	for _, pattern := range generatedFilePatterns {
		if pattern.MatchString(base) {
			return true
		}
	}

	// Check file header for generation markers
	if ec.isGeneratedFile(filename) {
		return true
	}

	for _, pattern := range ec.patterns {
		if matched, err := filepath.Match(pattern, base); err == nil && matched {
			return true
		}
		if matched, err := filepath.Match(pattern, filename); err == nil && matched {
			return true
		}
	}

	return false
}

// IsAridLine returns true if mutating this line would be low-value noise.
// Inspired by Google's "arid lines" concept — skip logging, metrics, comments, etc.
func (ec *ExclusionChecker) IsAridLine(filename string, line int, lineContent string) bool {
	key := fileLine{File: filename, Line: line}
	if cached, ok := ec.aridLineCache[key]; ok {
		return cached
	}

	trimmed := strings.TrimSpace(lineContent)
	arid := isAridContent(trimmed)
	ec.aridLineCache[key] = arid
	return arid
}

// IsAridNode returns true if the AST node is in an "arid" context
// (e.g., inside a log statement, defer, or pure boilerplate).
func IsAridNode(node ast.Node, fset *token.FileSet, fileLines []string) bool {
	if node == nil {
		return false
	}

	pos := fset.Position(node.Pos())
	if pos.Line <= 0 || pos.Line > len(fileLines) {
		return false
	}

	return isAridContent(strings.TrimSpace(fileLines[pos.Line-1]))
}

func (ec *ExclusionChecker) isGeneratedFile(filename string) bool {
	if cached, ok := ec.generatedCache[filename]; ok {
		return cached
	}

	generated := checkGeneratedFile(filename)
	ec.generatedCache[filename] = generated
	return generated
}

func checkGeneratedFile(filename string) bool {
	f, err := os.Open(filename)
	if err != nil {
		return false
	}
	defer f.Close()

	// Only check the first 20 lines for generation markers
	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() && lineNum < 20 {
		line := scanner.Text()
		lineNum++

		// Standard Go generated file marker
		// https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source
		if strings.Contains(line, "Code generated") && strings.Contains(line, "DO NOT EDIT") {
			return true
		}

		// protoc-gen-go
		if strings.Contains(line, "protoc-gen-go") {
			return true
		}

		// mockgen / mockery
		if strings.Contains(line, "Generated by mockgen") ||
			strings.Contains(line, "mockery") {
			return true
		}

		// wire
		if strings.Contains(line, "Injectors from") {
			return true
		}

		// stringer
		if strings.Contains(line, "stringer -type") {
			return true
		}

		// ent (entity framework)
		if strings.Contains(line, "by ent,") {
			return true
		}

		// sqlc
		if strings.Contains(line, "sqlc") && strings.Contains(line, "DO NOT EDIT") {
			return true
		}

		// gqlgen
		if strings.Contains(line, "gqlgen") {
			return true
		}

		// deepcopy-gen
		if strings.Contains(line, "deepcopy-gen") {
			return true
		}
	}

	return false
}

// isAridContent checks if a line of source code is "arid" — low value to mutate.
func isAridContent(trimmed string) bool {
	// Empty or comment-only lines
	if trimmed == "" || strings.HasPrefix(trimmed, "//") || strings.HasPrefix(trimmed, "/*") {
		return true
	}

	// Pure structural lines
	if trimmed == "{" || trimmed == "}" || trimmed == ")" || trimmed == "(" {
		return true
	}

	// Logging / tracing / metrics — mutating these rarely tests real behavior
	for _, pattern := range aridPrefixes {
		if strings.HasPrefix(trimmed, pattern) {
			return true
		}
	}

	// `// nolint` or `//nolint` tagged lines
	if strings.Contains(trimmed, "nolint") {
		return true
	}

	// `// mutagen:skip` pragma
	if strings.Contains(trimmed, "mutagen:skip") {
		return true
	}

	return false
}

// Directories to always skip
var excludedDirs = []string{
	"vendor",
	"testdata",
	"third_party",
	"node_modules",
	".git",
}

// Filename patterns for generated code
var generatedFilePatterns = []*regexp.Regexp{
	regexp.MustCompile(`\.pb\.go$`),        // protobuf
	regexp.MustCompile(`\.pb\.gw\.go$`),    // grpc-gateway
	regexp.MustCompile(`_gen\.go$`),        // common generated suffix
	regexp.MustCompile(`_generated\.go$`),  // common generated suffix
	regexp.MustCompile(`^zz_generated`),    // kubernetes-style generated
	regexp.MustCompile(`_string\.go$`),     // stringer output
	regexp.MustCompile(`mock_.*\.go$`),     // mockgen output
	regexp.MustCompile(`^mocks\.go$`),      // mockery output
	regexp.MustCompile(`wire_gen\.go$`),    // wire DI
	regexp.MustCompile(`_enumer\.go$`),     // enumer output
	regexp.MustCompile(`bindata\.go$`),     // go-bindata
	regexp.MustCompile(`\.deepcopy\.go$`),  // deepcopy-gen
	regexp.MustCompile(`\.resolvers\.go$`), // gqlgen resolvers
}

// Line prefixes that indicate low-value (arid) code
var aridPrefixes = []string{
	// Logging
	"log.", "logger.", "logging.",
	"slog.", "zap.", "logrus.",
	"klog.", "glog.",
	"fmt.Print", "fmt.Fprint", "fmt.Sprint",
	"t.Log", "t.Error", "t.Fatal", "t.Skip", // test helpers — shouldn't be in non-test code but just in case
	"b.Log",

	// Tracing / metrics
	"span.", "trace.", "metric.", "stats.",
	"prometheus.", "otel.",

	// Defer (usually cleanup, not business logic)
	"defer ",

	// Context plumbing
	"ctx = ", "ctx, cancel",

	// Import aliases
	"_ =",

	// Panic (usually unreachable)
	"panic(",
}

// containsPathSegment checks if the path contains the given directory segment.
func containsPathSegment(path, segment string) bool {
	// Match /vendor/ or vendor/ at the start
	sep := string(filepath.Separator)
	return strings.Contains(path, sep+segment+sep) ||
		strings.HasPrefix(path, segment+sep)
}
