package engine

import (
	"os"
	"path/filepath"
	"testing"
)

func TestExcludeTestFiles(t *testing.T) {
	ec := NewExclusionChecker(nil)
	if !ec.ShouldExcludeFile("foo_test.go") {
		t.Error("should exclude test files")
	}
	if ec.ShouldExcludeFile("foo.go") {
		t.Error("should not exclude regular files")
	}
}

func TestExcludeVendor(t *testing.T) {
	ec := NewExclusionChecker(nil)
	if !ec.ShouldExcludeFile("/project/vendor/pkg/foo.go") {
		t.Error("should exclude vendor files")
	}
}

func TestExcludeGeneratedPatterns(t *testing.T) {
	ec := NewExclusionChecker(nil)

	generated := []string{
		"foo.pb.go",
		"foo.pb.gw.go",
		"foo_gen.go",
		"foo_generated.go",
		"zz_generated_deepcopy.go",
		"foo_string.go",
		"mock_foo.go",
		"wire_gen.go",
	}
	for _, name := range generated {
		if !ec.ShouldExcludeFile("/project/" + name) {
			t.Errorf("should exclude %s", name)
		}
	}
}

func TestExcludeGeneratedHeader(t *testing.T) {
	ec := NewExclusionChecker(nil)
	dir := t.TempDir()

	// File with generation marker
	genFile := filepath.Join(dir, "gen.go")
	if err := os.WriteFile(genFile, []byte("// Code generated by foo. DO NOT EDIT.\npackage p\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if !ec.ShouldExcludeFile(genFile) {
		t.Error("should exclude file with Code generated header")
	}

	// File without marker
	normalFile := filepath.Join(dir, "normal.go")
	if err := os.WriteFile(normalFile, []byte("package p\nfunc f() {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if ec.ShouldExcludeFile(normalFile) {
		t.Error("should not exclude normal file")
	}
}

func TestExcludeUserPatterns(t *testing.T) {
	ec := NewExclusionChecker([]string{"*_mock.go", "internal_*.go"})

	if !ec.ShouldExcludeFile("/project/foo_mock.go") {
		t.Error("should exclude user pattern *_mock.go")
	}
	if !ec.ShouldExcludeFile("/project/internal_helpers.go") {
		t.Error("should exclude user pattern internal_*.go")
	}
	if ec.ShouldExcludeFile("/project/real.go") {
		t.Error("should not exclude non-matching file")
	}
}

func TestAridLines(t *testing.T) {
	arid := []string{
		"log.Printf(\"something\")",
		"defer f.Close()",
		"// this is a comment",
		"fmt.Println(err)",
		"slog.Info(\"msg\")",
		"panic(\"unreachable\")",
		"",
		"{",
		"}",
		"// mutagen:skip",
	}
	for i, line := range arid {
		ec := NewExclusionChecker(nil)
		if !ec.IsAridLine("test.go", i+1, line) {
			t.Errorf("should be arid: %q", line)
		}
	}

	notArid := []string{
		"if x > 0 {",
		"return a + b",
		"result := compute()",
		"for i := 0; i < n; i++ {",
		"x = y * z",
	}
	for i, line := range notArid {
		ec := NewExclusionChecker(nil)
		if ec.IsAridLine("test.go", i+1, line) {
			t.Errorf("should NOT be arid: %q", line)
		}
	}
}

func TestExcludeNonexistentFile(t *testing.T) {
	ec := NewExclusionChecker(nil)
	// Should not crash on nonexistent file — just return false (not generated)
	if ec.ShouldExcludeFile("/nonexistent/real_code.go") {
		t.Error("nonexistent file should not be excluded unless pattern matches")
	}
}

func TestExcludeThirdParty(t *testing.T) {
	ec := NewExclusionChecker(nil)
	if !ec.ShouldExcludeFile("/project/third_party/lib/foo.go") {
		t.Error("should exclude third_party directory")
	}
}

func TestExcludeTestdata(t *testing.T) {
	ec := NewExclusionChecker(nil)
	if !ec.ShouldExcludeFile("/project/testdata/fixture.go") {
		t.Error("should exclude testdata directory")
	}
}

func TestAridLineCache(t *testing.T) {
	ec := NewExclusionChecker(nil)

	// First call computes and caches
	result1 := ec.IsAridLine("test.go", 10, "log.Println(x)")
	// Second call should return cached value
	result2 := ec.IsAridLine("test.go", 10, "log.Println(x)")

	if result1 != result2 {
		t.Error("cached result should match")
	}
	if !result1 {
		t.Error("log.Println should be arid")
	}
}

func TestContainsPathSegment(t *testing.T) {
	tests := []struct {
		path    string
		segment string
		want    bool
	}{
		{"/project/vendor/pkg/foo.go", "vendor", true},
		{"/project/pkg/foo.go", "vendor", false},
		{"vendor/foo.go", "vendor", true},
		{"/project/myvendor/foo.go", "vendor", false}, // "myvendor" != "vendor"
		{"/project/testdata/foo.go", "testdata", true},
	}
	for _, tt := range tests {
		got := containsPathSegment(tt.path, tt.segment)
		if got != tt.want {
			t.Errorf("containsPathSegment(%q, %q) = %v, want %v", tt.path, tt.segment, got, tt.want)
		}
	}
}
